#!/usr/bin/env python3
"""15-iyul — 27-avgust to'plam yozuvi (EN + UZ)."""
import sys
sys.path.insert(0, "tools")
from build_log_post import build, fig, pair

EN = """
<p class="lede">Between 15 July and 27 August 2026 I shipped seven new websites, rebuilt an eighth, and spent most of the last week arguing with myself about a domain name. This is the whole log: every project, what it does, what broke, and what the traffic numbers actually say once you stop rounding them up.</p>

<p>Context, because it changes how you read the pace: I weld metal grilles in Tashkent for a living. All of this was built in the hours around that. Nothing here had a budget, a designer, or a second pair of eyes.</p>

<h2>21 July — CTN Language Centre</h2>

<p>An English school in Mirzo Ulug'bek district needed a site. I built one file: <code>index.html</code>, trilingual UZ/RU/EN with the language kept in <code>localStorage</code>, a light/dark toggle, scroll-reveal animations, and a lead form that copies the enquiry and opens Telegram. Courses, teachers, FAQ, a live Maps embed, and a mock-test teaser.</p>

<p>The palette started as cyan and ended as a clean DeepSeek-style blue, <code>#4D6BFE</code>, on a light, airy hero — the direction came from looking hard at DeepSeek, x.ai and Anthropic and deciding that Uzbek education sites overuse gradients.</p>

""" + fig("ctn.webp", "ctnlc.uz — one HTML file, three languages, dark mode, live map.", "CTN Language Centre homepage") + """

<p>Two things I'd do the same way again. First, the favicon set and the 1200×630 OG image were <em>generated by code</em> (a small Python script with cairosvg), not drawn by hand or by an image model — which means regenerating them after a colour change is one command. Second, the repo already contained a listening test and about 40 MB of MP3s, so the deploy had to go through the GitHub contents API rather than a force-push. I nearly wiped the audio. I didn't, but only because I checked first.</p>

<p>Search Console property verified the same day, sitemap submitted, and JSON-LD for <code>EducationalOrganization</code> + <code>LocalBusiness</code> — with no invented rating, because there isn't one yet. It lives at <a href="https://ctnlc.uz">ctnlc.uz</a>.</p>

<h2>23 July — ZED AVLOD School</h2>

<p>This one is family. A school in To'raqo'rg'on, Namangan region, running since 2020. Trilingual again, but the interesting part is the results table: thirteen real CEFR certificate scores, top result C1, several B2 — each one checkable against <code>sertifikat.uzbmb.uz</code>.</p>

""" + fig("zedavlod.webp", "zedavlod.uz — real CEFR results, no invented statistics.", "ZED AVLOD School homepage") + """

<p>What I left out matters more than what I put in: no certificate ID numbers, no photos of the students, and one official-looking portrait I found in the photo dump stayed out entirely because nobody had confirmed who it was. Captioning an unidentified person as "founder" would have been a lie with a face on it.</p>

<p>Full SEO stack: FAQ section with <code>FAQPage</code> schema, <code>EducationalOrganization</code> + <code>WebSite</code> JSON-LD with real coordinates, hreflang, its own GoatCounter site, Search Console verified, sitemap submitted. Live at <a href="https://zedavlod.uz">zedavlod.uz</a>.</p>

<h2>25 July — Chiziq</h2>

<p>A web studio, aimed squarely at being the cheaper and better-looking alternative to the incumbent in this market. It started life as <code>then.uz</code> and got renamed to <strong>chzq.uz</strong> — "Chiziq", Uzbek for "line" — because a brand people can say out loud in their own language beats a clever English pun. (Remember this paragraph. It happens again in six weeks.)</p>

""" + fig("chzq.webp", "chzq.uz — dark studio palette, and a portfolio you can actually open.", "Chiziq web studio homepage") + """

<p>The one real weapon on that site is the portfolio. Every studio in the country shows client testimonials; anyone can type a testimonial. So instead each project opens in a modal containing a <em>live iframe</em> of the actual site — flarestamina.com, zedavlod.uz, ctnlc.uz, the wedding-invite builder, the full mock platform, and my own portfolio. They're all on GitHub Pages, so no <code>X-Frame-Options</code> blocks the embed. The pitch is one line: not reviews — sites you can open right now.</p>

<p>Pricing is published, which is rarer here than it should be: landing 1.5 M, business site 3 M, catalogue/shop 6 M, Telegram bot 1.2 M, mini app 6 M so'm. Free prototype in 24 hours, pay after. Hosting 0 so'm, because static sites on GitHub Pages cost nothing to run and pretending otherwise is just markup.</p>

<h2>26 July — IELTS Hub, five times over</h2>

<p>No screenshot deserves its own figure here, because the visible result is a page that looks calmer. Five full redesign iterations of the Flarestamina hub, plus an audit that walked all 110 pages of the site and wrote down every broken thing. That audit is what set up the whole of August.</p>

<h2>1 August — Payvandchi</h2>

<p>My own workshop, finally with a site. Window grilles, balcony grilles, railings, canopies — and, importantly, <strong>no gates</strong>. We don't make them, so the word "darvoza" appears nowhere on the site, and I skipped every photo that showed a door grille rather than adding a service we can't deliver.</p>

""" + fig("payvandchi.webp", "payvandchi.maqsudjon.com — real work, real photos, no stock imagery.", "Payvandchi welding workshop homepage") + """

<p>Performance was the actual engineering here. The hero image landed at 521 KB, which on a Tashkent mobile connection is a visible wait. Re-encoded and resized to <strong>173 KB</strong> — a third of the weight, no visible difference. An English version followed on 5 August, and a fresh batch of workshop photos on 23 August. Adding a photo is two steps: a line in <code>categories.csv</code>, then <code>build-gallery.mjs</code>.</p>

<h2>4 August — Reshotkachi</h2>

<p>The same workshop and the same photographs, built a second time as a completely different site. Not laziness — a test. If the product is identical, how much does design alone change how it reads?</p>

""" + fig("reshotkachi.webp", "reshotkachi.maqsudjon.com — 123 photos, arranged as a 3D wall.", "Reshotkachi grille workshop homepage") + """

<p>Answer: a lot. This one arranges 123 photos into a three-dimensional gallery wall in UZ/RU/EN, and it feels like a different business to the one above. Same welder, same grilles.</p>

<h2>7 August — KVADRAT</h2>

<p>The least glamorous thing I built and possibly the most used. A square-metre calculator for grille jobs. You type three numbers — width, height, and how far the grille projects from the wall — and it computes the front face plus all four side faces.</p>

""" + fig("kvdrt.webp", "kvdrt.maqsudjon.com — three numbers in, a price-able area out.", "KVADRAT square metre calculator") + """

<p>The whole design problem was the input order. <code>120 130 30</code> has to mean width 120, height 130, projection 30, every time, for someone holding a tape measure with one hand. Getting that unambiguous took longer than the arithmetic.</p>

<h2>22 August — Flarestamina gets a paper design</h2>

<p>Flarestamina is my IELTS practice site: 113 test pages, each living in its own repository. It had grown into three products wearing one name — the hub was black and orange, the news section had its own palette, the account page looked like a third site.</p>

<p>Over one weekend the whole thing moved to a black-and-white "paper" design, page by page: the home page (rewritten as static HTML instead of being assembled by JavaScript), the tool pages, the news section, the account and content pages, the 404. Brand assets were redrawn, and the favicon and OG image URLs were versioned so browsers would actually pick up the new art instead of serving the old one from cache for a month.</p>

<p>The unglamorous wins in that pass: <strong>46 pages stopped calling Google</strong> for webfonts once they were self-hosted — and then I had to stop the build scripts helpfully re-adding the Google Fonts link on every rebuild. A rebuild had silently dropped structured data from some pages, so I restored it and taught the audit script to catch that specific regression. The privacy policy was brought back in line with what the site actually does now, and analytics gained a per-device opt-out.</p>

<h2>The hub stopped being a wall of links</h2>

<p>The practice hub is where everything starts, and it used to be a list. Now it asks one question — <em>choose a skill</em> — and gives you five cards: Listening (73 papers), Reading (25), Writing, Speaking, and the full mock. Above them, one card marked <em>start here</em> pointing at Cambridge 21: the whole book, four tests, all skills, free. Someone who has never used the site now has an obvious first click.</p>

""" + fig("fs-hub.webp", "The practice hub after the rebuild: one question, five cards, and an obvious place to start.", "Flarestamina practice hub") + """

<p>One catch the audit found: the hub builds its list in JavaScript, so a search-engine crawler arriving at it saw an empty page and none of the catalogue behind it. The fix was <code>/tests/</code> — a plain, static, crawlable index of every practice test on the site, which exists mostly so Google can read what a human can already see.</p>

<h2>News, and articles by people who aren't me</h2>

<p>The news section covers the thing Uzbek IELTS candidates actually search for and rarely find in one place: exam changes, fees, and scholarship deadlines. It now holds <strong>26 posts</strong> — 12 on the exam, 9 deadlines, 2 on fees, 2 guides — with a search box, category chips that carry their own counts, and three live cards at the top: the next deadline with a countdown, a score conversion, and the Telegram channel.</p>

""" + fig("fs-news.webp", "The news section: 26 posts, counted category chips, and the next deadline counting down at the top.", "Flarestamina news section") + """

<p><strong>Five of the posts are in Uzbek</strong>, and they open in Uzbek rather than making the reader find a toggle — the fee post in particular quotes figures read straight off the official booking page rather than repeated from memory. Every post got its own cover image, and the section publishes its own feed.</p>

<p>There are also six longer articles written through <code>/writearticle/</code>, the submission flow for teachers. Those are the first pages on the site with someone else's name on them, which is the point: a site that is only ever one person's voice has a ceiling.</p>

<h2>Five small tools</h2>

<p>Alongside the tests there's now a Tools menu, and everything in it is a single-purpose page that answers one question fast:</p>

<ul>
<li><strong>Score converter</strong> — IELTS ↔ CEFR ↔ Multilevel ↔ TOEFL, because every Uzbek university and embassy asks for a different scale.</li>
<li><strong>Scholarship deadlines</strong> — DAAD, Chevening, Erasmus Mundus, El-Yurt Umidi, CSC, GKS and the rest, with days remaining.</li>
<li><strong>Study plan generator</strong> — four questions (current band, target band, weeks left, weakest skill) and out comes a week-by-week plan plus an honest verdict on whether the timeline is enough or the exam should be moved. Telling someone to postpone is not what a conversion-optimised page does, and it's the most useful thing that tool says.</li>
<li><strong>Speaking topics</strong> — the current rotation.</li>
<li><strong>All tests</strong> — the crawlable catalogue index.</li>
</ul>

""" + fig("fs-tools.webp", "The study plan generator — four questions, and a verdict that will tell you to postpone the exam.", "Flarestamina study plan generator") + """

<p>They're generated rather than hand-written: each tool is a JSON-LD file plus a logic file, assembled by a build script, so adding the sixth one doesn't mean copying a page and forgetting to update the structured data.</p>

<h2>23–24 August — tearing down the login walls</h2>

<p>Traffic had been falling and I assumed it was an SEO problem. It wasn't. It was three login walls.</p>

<p>The hub that every one of those 113 tests hangs off called <code>FSAuth.require()</code>. So every single person arriving from Google was bounced straight to an account page before seeing anything. The Writing Lab had <em>two</em> gates — a login and a hardcoded access code. The speaking section had a third. All three are gone; login is now optional and only buys you saved results.</p>

""" + fig("flarestamina.webp", "flarestamina.com after the August rebuild — black and white, no gate.", "Flarestamina IELTS practice homepage") + """

<p>Then the actual SEO, done across 113 separate repositories via the GitHub API:</p>

<ul>
<li>Missing meta descriptions: <strong>101 → 0</strong>. Every description was generated from the page's own real H2 headings — the reading passage titles, the listening section topics — not written from imagination.</li>
<li>Missing canonical tags: <strong>107 → 1</strong>. Missing analytics: <strong>108 → 1</strong>. Duplicate titles: <strong>2 → 0</strong>.</li>
<li>JSON-LD structured data: <strong>0 → 106</strong> test pages, each with <code>LearningResource</code> and <code>BreadcrumbList</code>.</li>
<li>Titles rewritten to match what people actually search. <code>Mock Listening — Test 63 Listening</code> became <code>IELTS Listening Practice Test 63 with Answers</code>.</li>
<li>Three new landing pages: <code>/ielts-listening-test/</code> (73 tests), <code>/ielts-reading-test/</code> (25 tests), and <code>/uz/</code> for Uzbek-language search.</li>
<li>IndexNow key, hreflang, and a sitemap that stopped lying about <code>lastmod</code>.</li>
</ul>

<p>The audit also caught things that were quietly costing money and accuracy: a duplicated GoatCounter snippet that was <em>double-counting every pageview</em>, 65 pages still carrying a headline from a previous redesign, 522 MB of audio being served without any caching strategy, and nineteen reading pages that shared identical body text — which to a search engine reads as one page repeated nineteen times. Each got real, distinct content.</p>

<p>I also built <a href="https://flarestamina.com/stats/">flarestamina.com/stats/</a>: all seven sites' visitor counts in a single table, no login, no token. Checking seven dashboards was the reason I checked none of them.</p>

<h2>24–27 August — Tadam</h2>

<p>The newest one, and it gets its own post because it's the first thing I've built that is genuinely a product rather than a website: guests at a wedding scan a QR code on the table, upload the photos already on their phones, and the couple downloads all of them as a ZIP.</p>

""" + fig("tadam-home.webp", "tadam.uz — the whole flow explained above the fold.", "Tadam wedding photo album homepage") + """

<p>Full write-up here: <a href="/log/log-2026-08-27-tadam-wedding-photo-album.html">Tadam: a wedding photo album with no app and no database</a>.</p>

<h2>The rule underneath all of it</h2>

<p>One constraint ran through every project above: nothing invented. No fabricated review counts, no "500+ happy clients", no made-up ratings in the structured data, no student names attached to faces I couldn't verify, no "first and only in Uzbekistan" — which I was tempted by and which I left out, because I can't prove it and a claim you can't prove is just a nicer-sounding lie.</p>

<p>It costs something. A results table with thirteen honest CEFR scores looks smaller than one with a fake "98% success rate". But the thirteen are checkable on a government certificate database, and the 98% would have been checkable too — by anyone who wanted to embarrass me.</p>

<h2>What the numbers say</h2>

<p>Measured 23 August, and I'm quoting them exactly rather than rounding them into something impressive:</p>

<ul>
<li>Search Console, Flarestamina: <strong>911 impressions, 83 clicks, average position 11.1</strong>. Position 11 means page two. Page two is nowhere.</li>
<li>GoatCounter: <strong>238 visits in a week</strong>, of which Google accounted for about <strong>8%</strong>. Almost all real traffic is people sharing links directly.</li>
<li>Seven sites live, four on their own domains, all returning 200.</li>
</ul>

<p>The honest reading: the SEO work is a bet that hasn't paid out yet, and the sites that work are the ones somebody had a reason to send to a friend. That's worth knowing before I spend another six weeks on meta tags.</p>

<h2>Next</h2>

<p>Tadam needs real weddings on it, not test albums. The IELTS Hub redesign is built and waiting on a decision. Chiziq needs its first paying client. And I'd like the next six weeks to contain fewer new sites and more people actually using the existing ones.</p>
"""

UZ = """
<p class="lede">2026-yilning 15-iyulidan 27-avgustigacha yettita yangi sayt chiqardim, sakkizinchisini qaytadan qurdim va oxirgi haftaning ko'p qismini domen nomi ustida o'zim bilan tortishib o'tkazdim. Bu — to'liq jurnal: har bir loyiha, u nima qiladi, nima buzildi va raqamlarni yaxlitlamay o'qiganda ular aslida nima deyapti.</p>

<p>Sur'atni to'g'ri tushunish uchun kontekst: men Toshkentda panjara payvandlab kun ko'raman. Bularning hammasi shu ishning atrofidagi soatlarda qurilgan. Hech birining byudjeti, dizayneri yoki ikkinchi juft ko'zi bo'lmagan.</p>

<h2>21-iyul — CTN Language Centre</h2>

<p>Mirzo Ulug'bek tumanidagi ingliz tili markaziga sayt kerak edi. Bitta fayl qildim: <code>index.html</code> — UZ/RU/EN uch tilda (til <code>localStorage</code> da saqlanadi), yorug'/qorong'i rejim, skroll-animatsiyalar va so'rovni nusxalab Telegramni ochadigan lead-forma. Kurslar, o'qituvchilar, FAQ, jonli Google Maps va mock-testga ishora.</p>

<p>Palitra siyoh-moviydan boshlanib, toza DeepSeek uslubidagi ko'k <code>#4D6BFE</code> bilan tugadi — yo'nalish DeepSeek, x.ai va Anthropic saytlarini diqqat bilan ko'rib, o'zbek ta'lim saytlari gradientni haddan tashqari ko'p ishlatadi degan xulosadan chiqdi.</p>

""" + fig("ctn.webp", "ctnlc.uz — bitta HTML fayl, uch til, tungi rejim, jonli xarita.", "CTN Language Centre bosh sahifasi") + """

<p>Ikkita narsani yana shunday qilardim. Birinchisi — favicon to'plami va 1200×630 OG rasm <em>kod bilan yaratilgan</em> (cairosvg ishlatadigan kichik Python skript), qo'lda ham, rasm modeli bilan ham emas. Ya'ni rang o'zgarsa, hammasini bitta buyruq bilan qayta chiqarasiz. Ikkinchisi — repoda allaqachon listening test va ~40 MB MP3 bor edi, shuning uchun deploy force-push emas, GitHub contents API orqali qilindi. Audio fayllarni deyarli o'chirib yuborayozdim. O'chmadi — faqat oldindan tekshirganim uchun.</p>

<p>O'sha kuni Search Console tasdiqlandi, sitemap yuborildi, <code>EducationalOrganization</code> + <code>LocalBusiness</code> JSON-LD qo'shildi — soxta reytingsiz, chunki hali reyting yo'q. Manzil: <a href="https://ctnlc.uz">ctnlc.uz</a>.</p>

<h2>23-iyul — ZED AVLOD maktabi</h2>

<p>Bu — oilaviy ish. Namangan viloyati, To'raqo'rg'on tumanidagi maktab, 2020-yildan beri ishlaydi. Yana uch til, lekin eng qiziq joyi — natijalar jadvali: <strong>13 ta haqiqiy CEFR sertifikat bahosi</strong>, eng yuqorisi C1, bir nechtasi B2. Har birini <code>sertifikat.uzbmb.uz</code> dan tekshirsa bo'ladi.</p>

""" + fig("zedavlod.webp", "zedavlod.uz — haqiqiy CEFR natijalari, to'qilgan statistikasiz.", "ZED AVLOD maktabi bosh sahifasi") + """

<p>Nimani qo'shganimdan ko'ra nimani qo'shmaganim muhimroq: sertifikat raqamlari yo'q, o'quvchilar surati yo'q, va rasmlar orasidan chiqqan bitta rasmiy ko'rinishdagi portret butunlay tashqarida qoldi — chunki u kim ekanini hech kim tasdiqlamagan edi. Noma'lum odamni "asoschi" deb imzolash — yuzi bor yolg'on bo'lardi.</p>

<p>To'liq SEO: <code>FAQPage</code> sxemali FAQ bo'limi, haqiqiy koordinatali <code>EducationalOrganization</code> + <code>WebSite</code> JSON-LD, hreflang, alohida GoatCounter sayti, tasdiqlangan Search Console, yuborilgan sitemap. Jonli: <a href="https://zedavlod.uz">zedavlod.uz</a>.</p>

<h2>25-iyul — Chiziq</h2>

<p>Veb-studiya. Maqsad aniq: bu bozordagi yetakchidan arzonroq va chiroyliroq muqobil bo'lish. Avval <code>then.uz</code> nomi bilan boshlangan, keyin <strong>chzq.uz</strong> — "Chiziq" ga o'zgartirildi, chunki odamlar o'z tilida ovoz chiqarib ayta oladigan brend chiroyli inglizcha so'z o'yinidan kuchliroq. (Shu xatboshini eslab qoling. Olti hafta o'tib yana takrorlanadi.)</p>

""" + fig("chzq.webp", "chzq.uz — qorong'i studiya palitrasi va rostdan ochsa bo'ladigan portfolio.", "Chiziq veb-studiya bosh sahifasi") + """

<p>O'sha saytdagi yagona haqiqiy qurol — portfolio. Mamlakatdagi har bir studiya mijoz sharhlarini ko'rsatadi; sharhni esa har kim yozib qo'ya oladi. Shuning uchun bu yerda har bir loyiha modal oynada ochiladi va ichida haqiqiy saytning <em>jonli iframe</em> i turadi: flarestamina.com, zedavlod.uz, ctnlc.uz, to'y taklifnomasi builderi, full-mock platformasi va o'z portfoliom. Hammasi GitHub Pages'da, ya'ni <code>X-Frame-Options</code> to'smaydi. Xabar bir qator: sharh emas — hozir ochib ko'rsangiz bo'ladigan saytlar.</p>

<p>Narxlar ochiq yozilgan, bu bizda kerakligidan kamroq uchraydi: lending 1,5 mln · biznes sayt 3 mln · katalog/do'kon 6 mln · Telegram bot 1,2 mln · mini app 6 mln so'm. 24 soatda bepul prototip, to'lov keyin. Hosting 0 so'm — statik sayt GitHub Pages'da hech narsa turmaydi, boshqacha ko'rsatish shunchaki ustama bo'lardi.</p>

<h2>26-iyul — IELTS Hub, besh marta</h2>

<p>Bu yerda alohida skrinshot keraksiz, chunki ko'rinadigan natija — xotirjamroq sahifa. Flarestamina hub'ining beshta to'liq dizayn iteratsiyasi, ustiga saytning 110 sahifasini birma-bir aylanib chiqib, har bir buzuq joyni yozib chiqqan audit. O'sha audit butun avgust ishini belgilab berdi.</p>

<h2>1-avgust — Payvandchi</h2>

<p>O'z ustaxonam, nihoyat sayti bilan. Oyna panjarasi, balkon panjarasi, perila, kozirek — va, muhimi, <strong>darvoza yo'q</strong>. Biz darvoza yasamaymiz, shuning uchun bu so'z saytda umuman uchramaydi, eshik panjarasi ko'ringan har bir rasm ham chiqarib tashlandi. Qila olmaydigan xizmatni qo'shishdan ko'ra rasmni tashlagan yaxshi.</p>

""" + fig("payvandchi.webp", "payvandchi.maqsudjon.com — haqiqiy ish, haqiqiy rasmlar, stock rasmsiz.", "Payvandchi ustaxonasi bosh sahifasi") + """

<p>Bu yerdagi asosiy muhandislik ish — tezlik edi. Hero rasm 521 KB chiqdi, Toshkent mobil internetida bu ko'zga ko'rinadigan kutish. Qayta kodlab, o'lchamini kichraytirib <strong>173 KB</strong> ga tushirildi — vazn uchdan biriga, farq ko'rinmaydi. 5-avgustda inglizcha versiya, 23-avgustda ustaxonadan yangi rasmlar qo'shildi. Rasm qo'shish ikki qadam: <code>categories.csv</code> ga bir qator, keyin <code>build-gallery.mjs</code>.</p>

<h2>4-avgust — Reshotkachi</h2>

<p>O'sha ustaxona, o'sha rasmlar — butunlay boshqacha sayt sifatida ikkinchi marta qurildi. Bu dangasalik emas, sinov edi: mahsulot bir xil bo'lsa, faqat dizaynning o'zi uni qanchalik boshqacha ko'rsatadi?</p>

""" + fig("reshotkachi.webp", "reshotkachi.maqsudjon.com — 123 ta rasm, uch o'lchamli devor ko'rinishida.", "Reshotkachi panjara ustaxonasi bosh sahifasi") + """

<p>Javob: juda ko'p. Bu variant 123 ta rasmni UZ/RU/EN uch tilda uch o'lchamli galereya devoriga tizadi va yuqoridagidan butunlay boshqa biznesdek o'qiladi. Bir payvandchi, bir xil panjara.</p>

<h2>7-avgust — KVADRAT</h2>

<p>Eng jimjimasiz qurgan narsam va, ehtimol, eng ko'p ishlatiladigani. Panjara ishlari uchun kvadrat metr hisoblagich. Uchta raqam kiritasiz — eni, bo'yi va panjaraning devordan qancha chiqib turishi — u old yuza va to'rtta yon yuzani qo'shib hisoblaydi.</p>

""" + fig("kvdrt.webp", "kvdrt.maqsudjon.com — uchta raqam kiradi, narxlasa bo'ladigan yuza chiqadi.", "KVADRAT kvadrat metr hisoblagichi") + """

<p>Butun dizayn muammosi — kiritish tartibi edi. <code>120 130 30</code> har safar eni 120, bo'yi 130, vistup 30 degani bo'lishi kerak, ham bir qo'lida ruletka ushlab turgan odam uchun. Buni ikki xil o'qib bo'lmaydigan qilish arifmetikadan ko'proq vaqt oldi.</p>

<h2>22-avgust — Flarestamina "qog'oz" dizaynga o'tdi</h2>

<p>Flarestamina — mening IELTS mashq saytim: 113 ta test sahifasi, har biri alohida repoda yashaydi. U bitta nom ostida uchta boshqa-boshqa mahsulotga aylanib qolgan edi: hub qora-to'q sariq, news bo'limining o'z palitrasi, akkaunt sahifasi esa uchinchi saytdek ko'rinardi.</p>

<p>Bir dam olish kunida hammasi oq-qora "qog'oz" dizaynga ko'chdi, sahifama-sahifa: bosh sahifa (JavaScript yig'adigan emas, statik HTML qilib qayta yozildi), tool sahifalari, news bo'limi, akkaunt va kontent sahifalari, 404. Brend fayllari qaytadan chizildi, favicon va OG rasm manzillariga versiya qo'yildi — aks holda brauzer bir oy davomida keshdagi eskisini ko'rsatib turardi.</p>

<p>O'sha to'lqindagi jimjimasiz yutuqlar: shriftlar o'z serverimizga ko'chirilgach <strong>46 sahifa Google'ga murojaat qilishni to'xtatdi</strong> — keyin build skriptlarining har qayta qurishda Google Fonts havolasini "foydali" tarzda qaytadan qo'shishini to'xtatishga to'g'ri keldi. Qayta qurish ba'zi sahifalardan structured data'ni jimgina yo'qotgan ekan: tikladim va audit skriptiga aynan shu qaytalanishni tutishni o'rgatdim. Maxfiylik siyosati saytning hozirgi holatiga moslandi, analitikaga esa qurilma darajasida rad etish tugmasi qo'shildi.</p>

<h2>Hub havolalar devori bo'lishdan to'xtadi</h2>

<p>Mashq hub'i — hamma narsa boshlanadigan joy, va u ilgari shunchaki ro'yxat edi. Endi u bitta savol beradi — <em>qaysi ko'nikma?</em> — va beshta karta ko'rsatadi: Listening (73 ta variant), Reading (25 ta), Writing, Speaking va to'liq mock. Ularning tepasida <em>shu yerdan boshlang</em> deb belgilangan bitta karta: Cambridge 21 — butun kitob, to'rtta test, hamma ko'nikma, bepul. Saytni birinchi marta ochgan odam uchun endi aniq birinchi bosish bor.</p>

""" + fig("fs-hub.webp", "Qayta qurilgandan keyingi mashq hub'i: bitta savol, beshta karta va aniq boshlash nuqtasi.", "Flarestamina mashq hub'i") + """

<p>Audit topgan bitta tuzoq: hub o'z ro'yxatini JavaScript bilan yig'adi, ya'ni qidiruv roboti unga kelganda bo'sh sahifa ko'rardi va orqasidagi butun katalogni ko'rmasdi. Yechim — <code>/tests/</code>: saytdagi har bir mashq testining oddiy, statik, o'qish mumkin bo'lgan indeksi. U asosan Google odam allaqachon ko'rib turgan narsani o'qiy olsin deb bor.</p>

<h2>News va men yozmagan maqolalar</h2>

<p>News bo'limi o'zbek IELTS topshiruvchilari rostdan qidiradigan, lekin bir joyda kam topadigan narsani qamraydi: imtihondagi o'zgarishlar, narxlar va grant muddatlari. Hozir unda <strong>26 ta post</strong> bor — 12 tasi imtihon haqida, 9 tasi muddatlar, 2 tasi narx, 2 tasi qo'llanma — qidiruv maydoni, o'z sonini ko'tarib yuradigan kategoriya chiplari va tepada uchta jonli karta: eng yaqin muddat va unga qolgan kun, ball konvertatsiyasi, Telegram kanal.</p>

""" + fig("fs-news.webp", "News bo'limi: 26 ta post, sonli kategoriya chiplari va tepada sanab turgan eng yaqin muddat.", "Flarestamina news bo'limi") + """

<p><strong>Beshta post o'zbek tilida</strong>, va ular o'quvchini til tugmasini qidirishga majburlamay, to'g'ridan-to'g'ri o'zbekcha ochiladi — ayniqsa narx haqidagi post raqamlarni yoddan takrorlamay, rasmiy ro'yxatdan o'tish sahifasidan o'qib yozilgan. Har bir postga o'z muqova rasmi berildi, bo'limning o'z lentasi ham bor.</p>

<p>Yana <code>/writearticle/</code> — o'qituvchilar uchun maqola yuborish oqimi — orqali yozilgan oltita uzunroq maqola bor. Bular saytdagi birinchi begona nom turgan sahifalar, va gap aynan shunda: faqat bitta odamning ovozi bo'lgan saytning shifti past.</p>

<h2>Beshta kichik tool</h2>

<p>Testlar yonida endi Tools menyusi bor va undagi har bir narsa bitta savolga tez javob beradigan bitta maqsadli sahifa:</p>

<ul>
<li><strong>Ball konvertori</strong> — IELTS ↔ CEFR ↔ Multilevel ↔ TOEFL, chunki O'zbekistonda har bir universitet va elchixona boshqa shkalani so'raydi.</li>
<li><strong>Grant muddatlari</strong> — DAAD, Chevening, Erasmus Mundus, El-Yurt Umidi, CSC, GKS va boshqalar, qolgan kunlari bilan.</li>
<li><strong>O'quv reja generatori</strong> — to'rtta savol (hozirgi ball, maqsad ball, qolgan hafta, eng zaif ko'nikma) va chiqishda haftama-hafta reja hamda halol hukm: muddat yetadimi yoki imtihonni surish kerakmi. "Imtihonni suring" deyish konversiyaga sozlangan sahifa qiladigan ish emas — va bu o'sha toolning eng foydali gapi.</li>
<li><strong>Speaking mavzulari</strong> — joriy rotatsiya.</li>
<li><strong>Barcha testlar</strong> — robot o'qiy oladigan katalog indeksi.</li>
</ul>

""" + fig("fs-tools.webp", "O'quv reja generatori — to'rtta savol va sizga imtihonni surishni aytadigan hukm.", "Flarestamina o'quv reja generatori") + """

<p>Ular qo'lda yozilmaydi, generatsiya qilinadi: har bir tool = bitta JSON-LD fayl + bitta mantiq fayli, build skript ularni yig'adi. Shuning uchun oltinchisini qo'shish "sahifani nusxalab, structured data'ni yangilashni unutish" degani emas.</p>

<h2>23–24-avgust — login devorlarini buzish</h2>

<p>Tashrif kamayib borayotgandi va men buni SEO muammosi deb o'ylagandim. Unday emas ekan. Sabab — uchta login devori.</p>

<p>O'sha 113 ta test osilib turgan hub sahifasi <code>FSAuth.require()</code> ni chaqirardi. Ya'ni Google'dan kelgan har bir odam hech narsa ko'rmasdan to'g'ri akkaunt sahifasiga uchib ketardi. Writing Lab'da <em>ikkita</em> to'siq bor edi — login va kodga yozib qo'yilgan parol. Speaking bo'limida uchinchisi. Uchalasi ham yo'q; kirish endi ixtiyoriy va faqat natijani saqlash uchun kerak.</p>

""" + fig("flarestamina.webp", "avgust qayta qurilishidan keyingi flarestamina.com — oq-qora, to'siqsiz.", "Flarestamina IELTS mashq sayti bosh sahifasi") + """

<p>Keyin haqiqiy SEO — 113 ta alohida repoda, GitHub API orqali:</p>

<ul>
<li>Yo'q meta description: <strong>101 → 0</strong>. Har bir tavsif sahifaning o'z haqiqiy H2 sarlavhalaridan yasaldi — Reading matn nomlari, Listening bo'lim mavzulari — xayoldan yozilmadi.</li>
<li>Yo'q canonical: <strong>107 → 1</strong>. Yo'q analitika: <strong>108 → 1</strong>. Takroriy sarlavha: <strong>2 → 0</strong>.</li>
<li>JSON-LD structured data: <strong>0 → 106</strong> test sahifasi, har birida <code>LearningResource</code> va <code>BreadcrumbList</code>.</li>
<li>Sarlavhalar odamlar rostdan qidiradigan so'zlarga moslandi. <code>Mock Listening — Test 63 Listening</code> → <code>IELTS Listening Practice Test 63 with Answers</code>.</li>
<li>Uchta yangi kirish sahifasi: <code>/ielts-listening-test/</code> (73 test), <code>/ielts-reading-test/</code> (25 test) va o'zbekcha qidiruv uchun <code>/uz/</code>.</li>
<li>IndexNow kaliti, hreflang va <code>lastmod</code> bo'yicha yolg'on gapirishni bas qilgan sitemap.</li>
</ul>

<p>Audit jimgina pul va aniqlikni yeb turgan narsalarni ham topdi: dublikat GoatCounter kodi <em>har bir ko'rishni ikki marta sanayotgan edi</em>, 65 sahifada oldingi dizayndan qolgan sarlavha turardi, 522 MB audio hech qanday kesh siyosatisiz uzatilardi, va o'n to'qqizta Reading sahifasining matni bir xil edi — bu qidiruv tizimiga bitta sahifa o'n to'qqiz marta takrorlangandek ko'rinadi. Har biriga haqiqiy, alohida mazmun berildi.</p>

<p>Yana <a href="https://flarestamina.com/stats/">flarestamina.com/stats/</a> ni qurdim: yettala saytning tashrifi bitta jadvalda, loginsiz, tokensiz. Yettita dashboardni tekshirish kerakligi — aynan hech birini tekshirmasligimning sababi edi.</p>

<h2>24–27-avgust — Tadam</h2>

<p>Eng yangisi, va unga alohida maqola tegishli — chunki bu men qurgan birinchi narsa, u sayt emas, mahsulot: to'ydagi mehmonlar stoldagi QR kodni skanerlaydi, telefonidagi suratlarni yuklaydi, kelin-kuyov esa hammasini bitta ZIP qilib yuklab oladi.</p>

""" + fig("tadam-home.webp", "tadam.uz — butun jarayon birinchi ekranda tushuntirilgan.", "Tadam to'y foto albomi bosh sahifasi") + """

<p>To'liq yozuv shu yerda: <a href="/log/log-2026-08-27-tadam-wedding-photo-album-uz.html">Tadam: ilovasiz va ma'lumotlar bazasiz to'y albomi</a>.</p>

<h2>Hammasining ostidagi qoida</h2>

<p>Yuqoridagi har bir loyihadan bitta shart o'tgan: hech narsa to'qilmaydi. To'qilgan sharh soni yo'q, "500+ mamnun mijoz" yo'q, structured data ichida o'ylab topilgan reyting yo'q, tekshirolmaydigan yuzga yopishtirilgan o'quvchi ismi yo'q, "O'zbekistonda birinchi va yagona" yo'q — bunisi ko'nglimga kelgan edi va yozmadim, chunki isbotlay olmayman, isbotlab bo'lmaydigan da'vo esa shunchaki chiroyliroq eshitiladigan yolg'on.</p>

<p>Buning narxi bor. O'n uchta halol CEFR bahosi turgan jadval soxta "98% muvaffaqiyat" yozilganidan kichikroq ko'rinadi. Lekin o'sha o'n uchtasini davlat sertifikat bazasidan tekshirsa bo'ladi — 98% ni ham tekshirsa bo'lardi, meni uyaltirmoqchi bo'lgan har kim.</p>

<h2>Raqamlar nima deyapti</h2>

<p>23-avgustda o'lchandi. Ta'sirli ko'rinsin deb yaxlitlamay, borini yozaman:</p>

<ul>
<li>Search Console, Flarestamina: <strong>911 ko'rsatish, 83 klik, o'rtacha pozitsiya 11.1</strong>. 11-pozitsiya — ikkinchi sahifa. Ikkinchi sahifa esa hech qayer.</li>
<li>GoatCounter: bir haftada <strong>238 tashrif</strong>, shundan Google ulushi taxminan <strong>8%</strong>. Haqiqiy tashrifning deyarli hammasi — odamlar bir-biriga to'g'ridan-to'g'ri havola tashlagani.</li>
<li>Yettita sayt jonli, to'rttasi o'z domenida, hammasi 200 qaytaradi.</li>
</ul>

<p>Halol o'qilishi: SEO ishi — hali natija bermagan garov, ishlayotgan saytlar esa kimningdir do'stiga yuborishga sababi bo'lgan saytlar. Yana olti haftani meta teglarga sarflashdan oldin buni bilib qo'ygan yaxshi.</p>

<h2>Keyingisi</h2>

<p>Tadam'ga sinov albomlari emas, haqiqiy to'ylar kerak. IELTS Hub'ning yangi dizayni qurilgan va qaror kutyapti. Chiziq'ga birinchi pullik mijoz kerak. Va keyingi olti haftada yangi sayt kamroq, borlarini rostdan ishlatadigan odam ko'proq bo'lishini istardim.</p>
"""

EN_SLUG = "log-2026-08-27-seven-sites-six-weeks"
UZ_SLUG = "log-2026-08-27-seven-sites-six-weeks-uz"

build(EN_SLUG, "en",
      "Seven sites in six weeks",
      "Everything I shipped between 15 July and 27 August 2026: CTN, ZED AVLOD, "
      "Chiziq, Payvandchi, Reshotkachi, KVADRAT, the Flarestamina rebuild and Tadam "
      "— with screenshots and the real traffic numbers.",
      "27 AUG 2026", "2026-08-27", "ROUNDUP", EN,
      UZ_SLUG, "O'ZBEKCHA", "← ALL ENTRIES")

build(UZ_SLUG, "uz",
      "Olti haftada yettita sayt",
      "2026-yil 15-iyuldan 27-avgustgacha chiqarilgan hamma ish: CTN, ZED AVLOD, "
      "Chiziq, Payvandchi, Reshotkachi, KVADRAT, Flarestamina qayta qurilishi va "
      "Tadam — skrinshotlar va haqiqiy tashrif raqamlari bilan.",
      "27 AVG 2026", "2026-08-27", "TO'PLAM", UZ,
      EN_SLUG, "ENGLISH", "← BARCHA YOZUVLAR")

print("roundup: EN + UZ yozildi")
