#!/usr/bin/env python3
"""15-iyul — 27-avgust to'plam yozuvi (EN + UZ)."""
import sys
sys.path.insert(0, "tools")
from build_log_post import build, fig, pair

EN = """
<p class="lede">Between 15 July and 27 August 2026 I shipped seven new websites, rebuilt an eighth, and spent most of the last week arguing with myself about a domain name. This is the whole log: every project, what it does, what broke, and what the traffic numbers actually say once you stop rounding them up.</p>

<p>Context, because it changes how you read the pace: I weld metal grilles in Tashkent for a living. All of this was built in the hours around that. Nothing here had a budget, a designer, or a second pair of eyes.</p>

<h2>21 July — CTN Language Centre</h2>

<p>An English school in Mirzo Ulug'bek district needed a site. I built one file: <code>index.html</code>, trilingual UZ/RU/EN with the language kept in <code>localStorage</code>, a light/dark toggle, scroll-reveal animations, and a lead form that copies the enquiry and opens Telegram. Courses, teachers, FAQ, a live Maps embed, and a mock-test teaser.</p>

<p>The palette started as cyan and ended as a clean DeepSeek-style blue, <code>#4D6BFE</code>, on a light, airy hero — the direction came from looking hard at DeepSeek, x.ai and Anthropic and deciding that Uzbek education sites overuse gradients.</p>

""" + fig("ctn.webp", "ctnlc.uz — one HTML file, three languages, dark mode, live map.", "CTN Language Centre homepage") + """

<p>Two things I'd do the same way again. First, the favicon set and the 1200×630 OG image were <em>generated by code</em> (a small Python script with cairosvg), not drawn by hand or by an image model — which means regenerating them after a colour change is one command. Second, the repo already contained a listening test and about 40 MB of MP3s, so the deploy had to go through the GitHub contents API rather than a force-push. I nearly wiped the audio. I didn't, but only because I checked first.</p>

<p>Search Console property verified the same day, sitemap submitted, and JSON-LD for <code>EducationalOrganization</code> + <code>LocalBusiness</code> — with no invented rating, because there isn't one yet. It lives at <a href="https://ctnlc.uz">ctnlc.uz</a>.</p>

<h2>23 July — ZED AVLOD School</h2>

<p>This one is family. A school in To'raqo'rg'on, Namangan region, running since 2020. Trilingual again, but the interesting part is the results table: thirteen real CEFR certificate scores, top result C1, several B2 — each one checkable against <code>sertifikat.uzbmb.uz</code>.</p>

""" + fig("zedavlod.webp", "zedavlod.uz — real CEFR results, no invented statistics.", "ZED AVLOD School homepage") + """

<p>What I left out matters more than what I put in: no certificate ID numbers, no photos of the students, and one official-looking portrait I found in the photo dump stayed out entirely because nobody had confirmed who it was. Captioning an unidentified person as "founder" would have been a lie with a face on it.</p>

<p>Full SEO stack: FAQ section with <code>FAQPage</code> schema, <code>EducationalOrganization</code> + <code>WebSite</code> JSON-LD with real coordinates, hreflang, its own GoatCounter site, Search Console verified, sitemap submitted. Live at <a href="https://zedavlod.uz">zedavlod.uz</a>.</p>

<h2>25 July — Chiziq</h2>

<p>A web studio, aimed squarely at being the cheaper and better-looking alternative to the incumbent in this market. It started life as <code>then.uz</code> and got renamed to <strong>chzq.uz</strong> — "Chiziq", Uzbek for "line" — because a brand people can say out loud in their own language beats a clever English pun. (Remember this paragraph. It happens again in six weeks.)</p>

""" + fig("chzq.webp", "chzq.uz — dark studio palette, and a portfolio you can actually open.", "Chiziq web studio homepage") + """

<p>The one real weapon on that site is the portfolio. Every studio in the country shows client testimonials; anyone can type a testimonial. So instead each project opens in a modal containing a <em>live iframe</em> of the actual site — flarestamina.com, zedavlod.uz, ctnlc.uz, the wedding-invite builder, the full mock platform, and my own portfolio. They're all on GitHub Pages, so no <code>X-Frame-Options</code> blocks the embed. The pitch is one line: not reviews — sites you can open right now.</p>

<p>Pricing is published, which is rarer here than it should be: landing 1.5 M, business site 3 M, catalogue/shop 6 M, Telegram bot 1.2 M, mini app 6 M so'm. Free prototype in 24 hours, pay after. Hosting 0 so'm, because static sites on GitHub Pages cost nothing to run and pretending otherwise is just markup.</p>

<h2>26 July — IELTS Hub, five times over</h2>

<p>No screenshot deserves its own figure here, because the visible result is a page that looks calmer. Five full redesign iterations of the Flarestamina hub, plus an audit that walked all 110 pages of the site and wrote down every broken thing. That audit is what set up the whole of August.</p>

<h2>1 August — Payvandchi</h2>

<p>My own workshop, finally with a site. Window grilles, balcony grilles, railings, canopies — and, importantly, <strong>no gates</strong>. We don't make them, so the word "darvoza" appears nowhere on the site, and I skipped every photo that showed a door grille rather than adding a service we can't deliver.</p>

""" + fig("payvandchi.webp", "payvandchi.maqsudjon.com — real work, real photos, no stock imagery.", "Payvandchi welding workshop homepage") + """

<p>Performance was the actual engineering here. The hero image landed at 521 KB, which on a Tashkent mobile connection is a visible wait. Re-encoded and resized to <strong>173 KB</strong> — a third of the weight, no visible difference. An English version followed on 5 August, and a fresh batch of workshop photos on 23 August. Adding a photo is two steps: a line in <code>categories.csv</code>, then <code>build-gallery.mjs</code>.</p>

<h2>4 August — Reshotkachi</h2>

<p>The same workshop and the same photographs, built a second time as a completely different site. Not laziness — a test. If the product is identical, how much does design alone change how it reads?</p>

""" + fig("reshotkachi.webp", "reshotkachi.maqsudjon.com — 123 photos, arranged as a 3D wall.", "Reshotkachi grille workshop homepage") + """

<p>Answer: a lot. This one arranges 123 photos into a three-dimensional gallery wall in UZ/RU/EN, and it feels like a different business to the one above. Same welder, same grilles.</p>

<h2>7 August — KVADRAT</h2>

<p>The least glamorous thing I built and possibly the most used. A square-metre calculator for grille jobs. You type three numbers — width, height, and how far the grille projects from the wall — and it computes the front face plus all four side faces.</p>

""" + fig("kvdrt.webp", "kvdrt.maqsudjon.com — three numbers in, a price-able area out.", "KVADRAT square metre calculator") + """

<p>The whole design problem was the input order. <code>120 130 30</code> has to mean width 120, height 130, projection 30, every time, for someone holding a tape measure with one hand. Getting that unambiguous took longer than the arithmetic.</p>

<h2>22–24 August — Flarestamina: tearing down the walls</h2>

<p>Flarestamina is my IELTS practice site: 113 test pages, each in its own repository. Traffic had been falling and I assumed it was an SEO problem. It wasn't. It was three login walls.</p>

<p>The hub that every one of those 113 tests hangs off called <code>FSAuth.require()</code>. So every single person arriving from Google was bounced straight to an account page before seeing anything. The Writing Lab had <em>two</em> gates — a login and a hardcoded access code. The speaking section had a third. All three are gone; login is now optional and only buys you saved results.</p>

""" + fig("flarestamina.webp", "flarestamina.com after the August rebuild — black and white, no gate.", "Flarestamina IELTS practice homepage") + """

<p>Then the actual SEO, done across 113 separate repositories via the GitHub API:</p>

<ul>
<li>Missing meta descriptions: <strong>101 → 0</strong>. Every description was generated from the page's own real H2 headings — the reading passage titles, the listening section topics — not written from imagination.</li>
<li>Missing canonical tags: <strong>107 → 1</strong>. Missing analytics: <strong>108 → 1</strong>. Duplicate titles: <strong>2 → 0</strong>.</li>
<li>JSON-LD structured data: <strong>0 → 106</strong> test pages, each with <code>LearningResource</code> and <code>BreadcrumbList</code>.</li>
<li>Titles rewritten to match what people actually search. <code>Mock Listening — Test 63 Listening</code> became <code>IELTS Listening Practice Test 63 with Answers</code>.</li>
<li>Three new landing pages: <code>/ielts-listening-test/</code> (73 tests), <code>/ielts-reading-test/</code> (25 tests), and <code>/uz/</code> for Uzbek-language search.</li>
<li>IndexNow key, hreflang, and a sitemap that stopped lying about <code>lastmod</code>.</li>
</ul>

<p>The audit also caught things that were quietly costing money and accuracy: a duplicated GoatCounter snippet that was <em>double-counting every pageview</em>, 65 pages still carrying a headline from a previous redesign, 522 MB of audio being served without any caching strategy, and nineteen reading pages that shared identical body text — which to a search engine reads as one page repeated nineteen times. Each got real, distinct content.</p>

<p>I also built <a href="https://flarestamina.com/stats/">flarestamina.com/stats/</a>: all seven sites' visitor counts in a single table, no login, no token. Checking seven dashboards was the reason I checked none of them.</p>

<h2>24–27 August — Tadam</h2>

<p>The newest one, and it gets its own post because it's the first thing I've built that is genuinely a product rather than a website: guests at a wedding scan a QR code on the table, upload the photos already on their phones, and the couple downloads all of them as a ZIP.</p>

""" + fig("tadam-home.webp", "tadam.uz — the whole flow explained above the fold.", "Tadam wedding photo album homepage") + """

<p>Full write-up here: <a href="/log/log-2026-08-27-tadam-wedding-photo-album.html">Tadam: a wedding photo album with no app and no database</a>.</p>

<h2>The rule underneath all of it</h2>

<p>One constraint ran through every project above: nothing invented. No fabricated review counts, no "500+ happy clients", no made-up ratings in the structured data, no student names attached to faces I couldn't verify, no "first and only in Uzbekistan" — which I was tempted by and which I left out, because I can't prove it and a claim you can't prove is just a nicer-sounding lie.</p>

<p>It costs something. A results table with thirteen honest CEFR scores looks smaller than one with a fake "98% success rate". But the thirteen are checkable on a government certificate database, and the 98% would have been checkable too — by anyone who wanted to embarrass me.</p>

<h2>What the numbers say</h2>

<p>Measured 23 August, and I'm quoting them exactly rather than rounding them into something impressive:</p>

<ul>
<li>Search Console, Flarestamina: <strong>911 impressions, 83 clicks, average position 11.1</strong>. Position 11 means page two. Page two is nowhere.</li>
<li>GoatCounter: <strong>238 visits in a week</strong>, of which Google accounted for about <strong>8%</strong>. Almost all real traffic is people sharing links directly.</li>
<li>Seven sites live, four on their own domains, all returning 200.</li>
</ul>

<p>The honest reading: the SEO work is a bet that hasn't paid out yet, and the sites that work are the ones somebody had a reason to send to a friend. That's worth knowing before I spend another six weeks on meta tags.</p>

<h2>Next</h2>

<p>Tadam needs real weddings on it, not test albums. The IELTS Hub redesign is built and waiting on a decision. Chiziq needs its first paying client. And I'd like the next six weeks to contain fewer new sites and more people actually using the existing ones.</p>
"""

UZ = """
<p class="lede">2026-yilning 15-iyulidan 27-avgustigacha yettita yangi sayt chiqardim, sakkizinchisini qaytadan qurdim va oxirgi haftaning ko'p qismini domen nomi ustida o'zim bilan tortishib o'tkazdim. Bu — to'liq jurnal: har bir loyiha, u nima qiladi, nima buzildi va raqamlarni yaxlitlamay o'qiganda ular aslida nima deyapti.</p>

<p>Sur'atni to'g'ri tushunish uchun kontekst: men Toshkentda panjara payvandlab kun ko'raman. Bularning hammasi shu ishning atrofidagi soatlarda qurilgan. Hech birining byudjeti, dizayneri yoki ikkinchi juft ko'zi bo'lmagan.</p>

<h2>21-iyul — CTN Language Centre</h2>

<p>Mirzo Ulug'bek tumanidagi ingliz tili markaziga sayt kerak edi. Bitta fayl qildim: <code>index.html</code> — UZ/RU/EN uch tilda (til <code>localStorage</code> da saqlanadi), yorug'/qorong'i rejim, skroll-animatsiyalar va so'rovni nusxalab Telegramni ochadigan lead-forma. Kurslar, o'qituvchilar, FAQ, jonli Google Maps va mock-testga ishora.</p>

<p>Palitra siyoh-moviydan boshlanib, toza DeepSeek uslubidagi ko'k <code>#4D6BFE</code> bilan tugadi — yo'nalish DeepSeek, x.ai va Anthropic saytlarini diqqat bilan ko'rib, o'zbek ta'lim saytlari gradientni haddan tashqari ko'p ishlatadi degan xulosadan chiqdi.</p>

""" + fig("ctn.webp", "ctnlc.uz — bitta HTML fayl, uch til, tungi rejim, jonli xarita.", "CTN Language Centre bosh sahifasi") + """

<p>Ikkita narsani yana shunday qilardim. Birinchisi — favicon to'plami va 1200×630 OG rasm <em>kod bilan yaratilgan</em> (cairosvg ishlatadigan kichik Python skript), qo'lda ham, rasm modeli bilan ham emas. Ya'ni rang o'zgarsa, hammasini bitta buyruq bilan qayta chiqarasiz. Ikkinchisi — repoda allaqachon listening test va ~40 MB MP3 bor edi, shuning uchun deploy force-push emas, GitHub contents API orqali qilindi. Audio fayllarni deyarli o'chirib yuborayozdim. O'chmadi — faqat oldindan tekshirganim uchun.</p>

<p>O'sha kuni Search Console tasdiqlandi, sitemap yuborildi, <code>EducationalOrganization</code> + <code>LocalBusiness</code> JSON-LD qo'shildi — soxta reytingsiz, chunki hali reyting yo'q. Manzil: <a href="https://ctnlc.uz">ctnlc.uz</a>.</p>

<h2>23-iyul — ZED AVLOD maktabi</h2>

<p>Bu — oilaviy ish. Namangan viloyati, To'raqo'rg'on tumanidagi maktab, 2020-yildan beri ishlaydi. Yana uch til, lekin eng qiziq joyi — natijalar jadvali: <strong>13 ta haqiqiy CEFR sertifikat bahosi</strong>, eng yuqorisi C1, bir nechtasi B2. Har birini <code>sertifikat.uzbmb.uz</code> dan tekshirsa bo'ladi.</p>

""" + fig("zedavlod.webp", "zedavlod.uz — haqiqiy CEFR natijalari, to'qilgan statistikasiz.", "ZED AVLOD maktabi bosh sahifasi") + """

<p>Nimani qo'shganimdan ko'ra nimani qo'shmaganim muhimroq: sertifikat raqamlari yo'q, o'quvchilar surati yo'q, va rasmlar orasidan chiqqan bitta rasmiy ko'rinishdagi portret butunlay tashqarida qoldi — chunki u kim ekanini hech kim tasdiqlamagan edi. Noma'lum odamni "asoschi" deb imzolash — yuzi bor yolg'on bo'lardi.</p>

<p>To'liq SEO: <code>FAQPage</code> sxemali FAQ bo'limi, haqiqiy koordinatali <code>EducationalOrganization</code> + <code>WebSite</code> JSON-LD, hreflang, alohida GoatCounter sayti, tasdiqlangan Search Console, yuborilgan sitemap. Jonli: <a href="https://zedavlod.uz">zedavlod.uz</a>.</p>

<h2>25-iyul — Chiziq</h2>

<p>Veb-studiya. Maqsad aniq: bu bozordagi yetakchidan arzonroq va chiroyliroq muqobil bo'lish. Avval <code>then.uz</code> nomi bilan boshlangan, keyin <strong>chzq.uz</strong> — "Chiziq" ga o'zgartirildi, chunki odamlar o'z tilida ovoz chiqarib ayta oladigan brend chiroyli inglizcha so'z o'yinidan kuchliroq. (Shu xatboshini eslab qoling. Olti hafta o'tib yana takrorlanadi.)</p>

""" + fig("chzq.webp", "chzq.uz — qorong'i studiya palitrasi va rostdan ochsa bo'ladigan portfolio.", "Chiziq veb-studiya bosh sahifasi") + """

<p>O'sha saytdagi yagona haqiqiy qurol — portfolio. Mamlakatdagi har bir studiya mijoz sharhlarini ko'rsatadi; sharhni esa har kim yozib qo'ya oladi. Shuning uchun bu yerda har bir loyiha modal oynada ochiladi va ichida haqiqiy saytning <em>jonli iframe</em> i turadi: flarestamina.com, zedavlod.uz, ctnlc.uz, to'y taklifnomasi builderi, full-mock platformasi va o'z portfoliom. Hammasi GitHub Pages'da, ya'ni <code>X-Frame-Options</code> to'smaydi. Xabar bir qator: sharh emas — hozir ochib ko'rsangiz bo'ladigan saytlar.</p>

<p>Narxlar ochiq yozilgan, bu bizda kerakligidan kamroq uchraydi: lending 1,5 mln · biznes sayt 3 mln · katalog/do'kon 6 mln · Telegram bot 1,2 mln · mini app 6 mln so'm. 24 soatda bepul prototip, to'lov keyin. Hosting 0 so'm — statik sayt GitHub Pages'da hech narsa turmaydi, boshqacha ko'rsatish shunchaki ustama bo'lardi.</p>

<h2>26-iyul — IELTS Hub, besh marta</h2>

<p>Bu yerda alohida skrinshot keraksiz, chunki ko'rinadigan natija — xotirjamroq sahifa. Flarestamina hub'ining beshta to'liq dizayn iteratsiyasi, ustiga saytning 110 sahifasini birma-bir aylanib chiqib, har bir buzuq joyni yozib chiqqan audit. O'sha audit butun avgust ishini belgilab berdi.</p>

<h2>1-avgust — Payvandchi</h2>

<p>O'z ustaxonam, nihoyat sayti bilan. Oyna panjarasi, balkon panjarasi, perila, kozirek — va, muhimi, <strong>darvoza yo'q</strong>. Biz darvoza yasamaymiz, shuning uchun bu so'z saytda umuman uchramaydi, eshik panjarasi ko'ringan har bir rasm ham chiqarib tashlandi. Qila olmaydigan xizmatni qo'shishdan ko'ra rasmni tashlagan yaxshi.</p>

""" + fig("payvandchi.webp", "payvandchi.maqsudjon.com — haqiqiy ish, haqiqiy rasmlar, stock rasmsiz.", "Payvandchi ustaxonasi bosh sahifasi") + """

<p>Bu yerdagi asosiy muhandislik ish — tezlik edi. Hero rasm 521 KB chiqdi, Toshkent mobil internetida bu ko'zga ko'rinadigan kutish. Qayta kodlab, o'lchamini kichraytirib <strong>173 KB</strong> ga tushirildi — vazn uchdan biriga, farq ko'rinmaydi. 5-avgustda inglizcha versiya, 23-avgustda ustaxonadan yangi rasmlar qo'shildi. Rasm qo'shish ikki qadam: <code>categories.csv</code> ga bir qator, keyin <code>build-gallery.mjs</code>.</p>

<h2>4-avgust — Reshotkachi</h2>

<p>O'sha ustaxona, o'sha rasmlar — butunlay boshqacha sayt sifatida ikkinchi marta qurildi. Bu dangasalik emas, sinov edi: mahsulot bir xil bo'lsa, faqat dizaynning o'zi uni qanchalik boshqacha ko'rsatadi?</p>

""" + fig("reshotkachi.webp", "reshotkachi.maqsudjon.com — 123 ta rasm, uch o'lchamli devor ko'rinishida.", "Reshotkachi panjara ustaxonasi bosh sahifasi") + """

<p>Javob: juda ko'p. Bu variant 123 ta rasmni UZ/RU/EN uch tilda uch o'lchamli galereya devoriga tizadi va yuqoridagidan butunlay boshqa biznesdek o'qiladi. Bir payvandchi, bir xil panjara.</p>

<h2>7-avgust — KVADRAT</h2>

<p>Eng jimjimasiz qurgan narsam va, ehtimol, eng ko'p ishlatiladigani. Panjara ishlari uchun kvadrat metr hisoblagich. Uchta raqam kiritasiz — eni, bo'yi va panjaraning devordan qancha chiqib turishi — u old yuza va to'rtta yon yuzani qo'shib hisoblaydi.</p>

""" + fig("kvdrt.webp", "kvdrt.maqsudjon.com — uchta raqam kiradi, narxlasa bo'ladigan yuza chiqadi.", "KVADRAT kvadrat metr hisoblagichi") + """

<p>Butun dizayn muammosi — kiritish tartibi edi. <code>120 130 30</code> har safar eni 120, bo'yi 130, vistup 30 degani bo'lishi kerak, ham bir qo'lida ruletka ushlab turgan odam uchun. Buni ikki xil o'qib bo'lmaydigan qilish arifmetikadan ko'proq vaqt oldi.</p>

<h2>22–24-avgust — Flarestamina: devorlarni buzish</h2>

<p>Flarestamina — mening IELTS mashq saytim: 113 ta test sahifasi, har biri alohida repoda. Tashrif kamayib borayotgandi va men buni SEO muammosi deb o'ylagandim. Unday emas ekan. Sabab — uchta login devori.</p>

<p>O'sha 113 ta test osilib turgan hub sahifasi <code>FSAuth.require()</code> ni chaqirardi. Ya'ni Google'dan kelgan har bir odam hech narsa ko'rmasdan to'g'ri akkaunt sahifasiga uchib ketardi. Writing Lab'da <em>ikkita</em> to'siq bor edi — login va kodga yozib qo'yilgan parol. Speaking bo'limida uchinchisi. Uchalasi ham yo'q; kirish endi ixtiyoriy va faqat natijani saqlash uchun kerak.</p>

""" + fig("flarestamina.webp", "avgust qayta qurilishidan keyingi flarestamina.com — oq-qora, to'siqsiz.", "Flarestamina IELTS mashq sayti bosh sahifasi") + """

<p>Keyin haqiqiy SEO — 113 ta alohida repoda, GitHub API orqali:</p>

<ul>
<li>Yo'q meta description: <strong>101 → 0</strong>. Har bir tavsif sahifaning o'z haqiqiy H2 sarlavhalaridan yasaldi — Reading matn nomlari, Listening bo'lim mavzulari — xayoldan yozilmadi.</li>
<li>Yo'q canonical: <strong>107 → 1</strong>. Yo'q analitika: <strong>108 → 1</strong>. Takroriy sarlavha: <strong>2 → 0</strong>.</li>
<li>JSON-LD structured data: <strong>0 → 106</strong> test sahifasi, har birida <code>LearningResource</code> va <code>BreadcrumbList</code>.</li>
<li>Sarlavhalar odamlar rostdan qidiradigan so'zlarga moslandi. <code>Mock Listening — Test 63 Listening</code> → <code>IELTS Listening Practice Test 63 with Answers</code>.</li>
<li>Uchta yangi kirish sahifasi: <code>/ielts-listening-test/</code> (73 test), <code>/ielts-reading-test/</code> (25 test) va o'zbekcha qidiruv uchun <code>/uz/</code>.</li>
<li>IndexNow kaliti, hreflang va <code>lastmod</code> bo'yicha yolg'on gapirishni bas qilgan sitemap.</li>
</ul>

<p>Audit jimgina pul va aniqlikni yeb turgan narsalarni ham topdi: dublikat GoatCounter kodi <em>har bir ko'rishni ikki marta sanayotgan edi</em>, 65 sahifada oldingi dizayndan qolgan sarlavha turardi, 522 MB audio hech qanday kesh siyosatisiz uzatilardi, va o'n to'qqizta Reading sahifasining matni bir xil edi — bu qidiruv tizimiga bitta sahifa o'n to'qqiz marta takrorlangandek ko'rinadi. Har biriga haqiqiy, alohida mazmun berildi.</p>

<p>Yana <a href="https://flarestamina.com/stats/">flarestamina.com/stats/</a> ni qurdim: yettala saytning tashrifi bitta jadvalda, loginsiz, tokensiz. Yettita dashboardni tekshirish kerakligi — aynan hech birini tekshirmasligimning sababi edi.</p>

<h2>24–27-avgust — Tadam</h2>

<p>Eng yangisi, va unga alohida maqola tegishli — chunki bu men qurgan birinchi narsa, u sayt emas, mahsulot: to'ydagi mehmonlar stoldagi QR kodni skanerlaydi, telefonidagi suratlarni yuklaydi, kelin-kuyov esa hammasini bitta ZIP qilib yuklab oladi.</p>

""" + fig("tadam-home.webp", "tadam.uz — butun jarayon birinchi ekranda tushuntirilgan.", "Tadam to'y foto albomi bosh sahifasi") + """

<p>To'liq yozuv shu yerda: <a href="/log/log-2026-08-27-tadam-wedding-photo-album-uz.html">Tadam: ilovasiz va ma'lumotlar bazasiz to'y albomi</a>.</p>

<h2>Hammasining ostidagi qoida</h2>

<p>Yuqoridagi har bir loyihadan bitta shart o'tgan: hech narsa to'qilmaydi. To'qilgan sharh soni yo'q, "500+ mamnun mijoz" yo'q, structured data ichida o'ylab topilgan reyting yo'q, tekshirolmaydigan yuzga yopishtirilgan o'quvchi ismi yo'q, "O'zbekistonda birinchi va yagona" yo'q — bunisi ko'nglimga kelgan edi va yozmadim, chunki isbotlay olmayman, isbotlab bo'lmaydigan da'vo esa shunchaki chiroyliroq eshitiladigan yolg'on.</p>

<p>Buning narxi bor. O'n uchta halol CEFR bahosi turgan jadval soxta "98% muvaffaqiyat" yozilganidan kichikroq ko'rinadi. Lekin o'sha o'n uchtasini davlat sertifikat bazasidan tekshirsa bo'ladi — 98% ni ham tekshirsa bo'lardi, meni uyaltirmoqchi bo'lgan har kim.</p>

<h2>Raqamlar nima deyapti</h2>

<p>23-avgustda o'lchandi. Ta'sirli ko'rinsin deb yaxlitlamay, borini yozaman:</p>

<ul>
<li>Search Console, Flarestamina: <strong>911 ko'rsatish, 83 klik, o'rtacha pozitsiya 11.1</strong>. 11-pozitsiya — ikkinchi sahifa. Ikkinchi sahifa esa hech qayer.</li>
<li>GoatCounter: bir haftada <strong>238 tashrif</strong>, shundan Google ulushi taxminan <strong>8%</strong>. Haqiqiy tashrifning deyarli hammasi — odamlar bir-biriga to'g'ridan-to'g'ri havola tashlagani.</li>
<li>Yettita sayt jonli, to'rttasi o'z domenida, hammasi 200 qaytaradi.</li>
</ul>

<p>Halol o'qilishi: SEO ishi — hali natija bermagan garov, ishlayotgan saytlar esa kimningdir do'stiga yuborishga sababi bo'lgan saytlar. Yana olti haftani meta teglarga sarflashdan oldin buni bilib qo'ygan yaxshi.</p>

<h2>Keyingisi</h2>

<p>Tadam'ga sinov albomlari emas, haqiqiy to'ylar kerak. IELTS Hub'ning yangi dizayni qurilgan va qaror kutyapti. Chiziq'ga birinchi pullik mijoz kerak. Va keyingi olti haftada yangi sayt kamroq, borlarini rostdan ishlatadigan odam ko'proq bo'lishini istardim.</p>
"""

EN_SLUG = "log-2026-08-27-seven-sites-six-weeks"
UZ_SLUG = "log-2026-08-27-seven-sites-six-weeks-uz"

build(EN_SLUG, "en",
      "Seven sites in six weeks",
      "Everything I shipped between 15 July and 27 August 2026: CTN, ZED AVLOD, "
      "Chiziq, Payvandchi, Reshotkachi, KVADRAT, the Flarestamina rebuild and Tadam "
      "— with screenshots and the real traffic numbers.",
      "27 AUG 2026", "2026-08-27", "ROUNDUP", EN,
      UZ_SLUG, "O'ZBEKCHA", "← ALL ENTRIES")

build(UZ_SLUG, "uz",
      "Olti haftada yettita sayt",
      "2026-yil 15-iyuldan 27-avgustgacha chiqarilgan hamma ish: CTN, ZED AVLOD, "
      "Chiziq, Payvandchi, Reshotkachi, KVADRAT, Flarestamina qayta qurilishi va "
      "Tadam — skrinshotlar va haqiqiy tashrif raqamlari bilan.",
      "27 AVG 2026", "2026-08-27", "TO'PLAM", UZ,
      EN_SLUG, "ENGLISH", "← BARCHA YOZUVLAR")

print("roundup: EN + UZ yozildi")
